UCLAdeepvision/CS188-Projects-2023Winter

_posts/2023-01-27-team15-deepfake-generation.md

team15-week3

---

_posts/2023-01-26-team12-diffusion-models.md

Project Proposal
Team 12: Dave Ho,  Anthony Zhu
* Post markdown file created
* Project proposal added to markdown file

team12-week3

---

_posts/2023-01-26-team14-deep-fake-generation.md

team14-week3

---

_posts/2023-01-28-team05-pose-estimation.md

* Create Markdown post file for team project
* Add proposal details to post

team05-week03

---

_posts/2023-01-26-team10-pose-estimation.md

Topic chosen + 3 relevant research papers

team10-week3

---

_posts/2023-01-28-team01-deepfake-detection.md

This is a submission for Janice Tsai and Zachary Chang. Please review our proposal! Thank you.

team01-week3

---

_posts/2023-01-28-team40-Clip_and_some_application.md

Add folder in image and add a post

---

_posts/2023-01-27-team37-projectmedimgs.md

Project Proposal with relevant links

Team 37-Week 3

---

_posts/2023-01-29-team39-AstroCV.md

team39-week3

---

_posts/2022-01-29-team31-object-boxes.md

project proposal for team 31 with Ryan Vuong and Travis Graening

team31-week3

---

_posts/2023-01-29-team24-deepfake-detection.md

team24-proposal

---

_posts/2023-01-29-team32-trajectory-prediction.md
assets/images/team32/placeholder.txt

team32-week3

---

_posts/2023-01-29-team42-image-similarity.md

team42-proposal

---

_posts/2023-01-29-team29-medical-imaging.md

project prop

---

_posts/2023-01-29-team47-deep-learning-dance.md

Team 47 Proposal

---

_posts/2023-01-29-team50-3Dfrom2D.md

Add project proposal for team50

---

_posts/2023-01-29-team04-object_detection.md

team04-week4

---

_posts/2023-01-29-team19-clip.md

add proposal

---

_posts/2023-01-29-team04-object_detection.md

team04-week7

---

_posts/2023-01-29-team48-object-detection.md

team48-week7

---

_posts/2023-01-28-team09-AnimeGAN.md

Fix latax expression, previously not displaying on web view

team09-week7

---

_posts/2023-02-24-team23-adversarial-example.md

I find that the github could not correct display the equations with \left\{ and \right\}, but it could be correctly displayed locally.

fix my format issues

---

_posts/2023-01-29-team19-clip.md

correct typo in title

---

_posts/2023-01-28-team01-deepfake-detection.md

Complete final project for CS188.

team01-complete final project
